# Generated by Django 2.2.7 on 2019-12-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
        ('Albumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumes',
            name='fecha',
        ),
        migrations.AddField(
            model_name='albumes',
            name='artista',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artistas.Artista'),
        ),
    ]
